language: python
python:
  - "2.7"
sudo: required
install:
  - "sudo apt-get install gfortran python-liblas libblas-dev liblapack-dev libatlas-dev"
  - "pip install -r requirements.txt"
script:
  - ls $HOME/builds
  - ls $HOME/build
  - cd $HOME/build/edublancas/sklearn-evaluation
  - ./run_tests